# 全局配置

spring:
  profiles:
    active: dev
  http:
    multipart:
      enabled: true
      max-file-size: 1MB
      max-request-size:  1MB

#  mvc:
#    static-path-pattern: classpath:/stati/, classpath:/templates/static/


  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rds7349m0p48u5q9182j.mysql.rds.aliyuncs.com/TYSCM?useUnicode=true&characterEncoding=utf8
    username: tyscm
    password: Tyscm123
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    # filters: stat,wall,log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    # connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    # useGlobalDataSourceStat: true

  freemarker:
    cache: false
    charset: utf-8
    content-type: text/html
    check-template-location: true
    expose-request-attributes: true
    expose-session-attributes: true
    expose-spring-macro-helpers: true
    suffix: .ftl
    template-loader-path: ["classpath:/templates/"]
    view-names: default
    order: 0



mybatis:
  configuration:
    call-setters-on-nulls: true
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/com/hansy/tyly/**/mapper/xml/*Mapper.xml
  type-aliases-package: com.hansy.tyly.**.model

  # mybatis.pagehelper
pagehelper:
  # 数据库类型
  helperDialect: mysql
  # 启用合理化时，如果pageNum<1会查询第一页，如果pageNum>pages会查询最后一页
  reasonable: true
  # 相当于没有执行分页查询，但是返回结果仍然是Page类型
  pageSizeZero: true
  # 支持通过Mapper接口参数来传递分页参数
  supportMethodsArguments: true
  # 配置pageNum,pageSize,count,pageSizeZero,reasonable,orderBy,不配置映射的用默认值
  params: count=countSql;pageNum=pageNo;pageSize=pageSize;orderBy=orderBy

# mybatis.mapper
# mappers 多个接口时逗号隔开
mapper:
  mappers: tk.mybatis.mapper.common.Mapper
  notEmpty: false
  identity: MYSQL
server:
  session:
    cookie:
      http-only: true
      name: 'SID_${random.uuid()}'
      # 仅适用https
      # secure: true
    # 单位秒 1 * 60 * 30 = 30分钟
    timeout: 18000

logging:
  level:
    root: info
    apache:
      ibatis: debug
    org:
      mybatis: debug
    com:
      lemoncome: trace
      ibatis: debug
