# prod(生产环境)

spring:
  # 数据库连接
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-wz9yt1cabi64vmxh7ho.mysql.rds.aliyuncs.com:3306/watchdog-proddb?useUnicode=true&amp;characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: prodwatchdogdb
    password: 1ls2Ningmeng
    initialSize: 20
    minIdle: 20
    maxActive: 100