
spring:
  profiles:
    # 运行环境
    active: dev

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-m5ej43sv394jnf7x0o.mysql.rds.aliyuncs.com:3306/watchdog-devdb?useUnicode=true&amp;characterEncoding=utf-8
    username: watchdog
    password: 1ls2Ningmeng
    #url: jdbc:mysql://127.0.0.1:3306/watchdog-devdb?useUnicode=true&amp;characterEncoding=utf-8
    #username: root
    #password: wb1234
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    # filters: stat,wall,log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    # connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    # useGlobalDataSourceStat: true


mybatis:
  configuration:
    call-setters-on-nulls: true
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/com/lemoncome/watchdog/**/mapper/xml/*Mapper.xml
  type-aliases-package: com.lemoncome.watchdog.**.model


# mybatis.mapper
# mappers 多个接口时逗号隔开
mapper:
  mappers: tk.mybatis.mapper.common.Mapper
  notEmpty: false
  identity: MYSQL
server:
  session:
    # 单位秒
    timeout: 1800

logging:
  file: ./logs/batchInfo.log
  level:
    root: info
    apache:
      ibatis: debug
    org:
      mybatis: debug
    com:
      lemoncome: trace
      ibatis: debug